/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_manning_sdmia_osgi_nativecode_Calculator */

#ifndef _Included_com_manning_sdmia_osgi_nativecode_Calculator
#define _Included_com_manning_sdmia_osgi_nativecode_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_manning_sdmia_osgi_nativecode_Calculator
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_manning_sdmia_osgi_nativecode_Calculator_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
